use restaurant;
insert into Plato (`nombre`,
 `Primavera`, `Verano`, `Otono`, `Invierno`, `Gluten`, `Crustaceo`, `Huevo`, `Pescado`, `Cacahuete`,
 `Soja`, `Lacteos`, `Cascara`, `Apio`, `Mostaza`, `Sesamo`, `Sulfitos`, `Altramuces`, `Moluscos`, `Visible`) VALUES 
 ("Espaguetis con salsa de tomate y perejil", 
 true, false, false, true, true, false, false, false, false, 
 false, false, false, false, false, false, false, false, false, true),
 ("Ensalada de Pasta con atún desmenuzado", 
 false, true, false, false, true, false, false, true, false, 
 false, false, false, false, false, false, false, false, false, true),
 ("Ensalada clásica", 
 true, true, false, false, false, false, false, false, false, 
 false, false, false, false, false, false, false, false, false, true),
 ("Ensalada Surtida con aliño de Pedro Ximénez", 
 true, true, false, false, false, false, true, true, true, 
 true, false, false, true, false, false, true, false, false, true),
 ("Sopa de pollo con picatostes", 
 false, false, true, true, true, false, false, false, false, 
 false, false, false, false, false, false, false, false, false, true),
 ("San Jacobos con queso serrano", 
 true, false, true, true, true, false, true, false, false, 
 false, false, false, false, false, false, false, false, false, true),
 ("Revuelto saludable (Vegetariano)",
 true, true, true, true, true, false, false, false, true,
 true, false, true, true, false, true, true, true, false, true),
 ("Secreto ibérico con revuelto de setas",
 true, true, true, true, false, false, true, false, false,
 false, false, false, false, false, false, false, false, false, true),
 ("Croquetas 'Dos Jamones'",
 true, true, true, true, true, false, true, false, false,
 false, true, false, false, false, false, false, false, false, true),
 ("Costillas a la brasa",
 true, true, true, true, false, false, false, false, false,
 false, false, false, false, false, false, false, false, false, true),
 ("Chuletón con salsa especial de la casa",
 true, true, true, true, false, false, false, false, false,
 true, true, false, false, true, false, false, false, false, true),
 ("Mezcla de albóndigas de vacuno y cerdo con tomate",
 true, true, true, true, true, false, true, false, false,
 false, false, false, false, false, false, false, false, false, true),
 ("Patatas asadas con queso y pastrami",
 false, false, true, true, false, false, false, false, false,
 false, true, false, false, false, false, true, false, false, true);
 
 /* Password = paso */
 insert into Config (`Temporada`, `Password`) VALUES 
 ("Primavera", "d63c223383eae016bdd35fd0521e00dabf533b2485f80bae195277a0b5079f50ec286cacea7dc21cc8b849451d7c7226d6616df3e8a92829180ee83ceb71cfa0");